# Generated by Django 3.1.3 on 2020-11-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineItems',
            new_name='LineItem',
        ),
    ]
