# Generated by Django 3.1.3 on 2020-11-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201128_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
